#pragma once
#include <Arduino.h>

const char WEB_UI[] PROGMEM = R"HTML(<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ESP32 Sensor</title>
<style>
:root{color-scheme:dark;--bg:#0b1019;--panel:#141e2b;--line:#29394c;--text:#e7eef8;--muted:#94a8be;--accent:#66e1c2}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}header{padding:24px 5vw;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:16px}h1{font-size:22px;margin:0}small,.muted{color:var(--muted)}nav{display:flex;gap:8px;padding:20px 5vw 0}button{cursor:pointer;background:#243449;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:11px 16px;font:inherit}button.active,button.primary{background:var(--accent);color:#0c2420;border-color:var(--accent)}button:disabled{opacity:.5;cursor:wait}main{padding:24px 5vw;max-width:1500px;margin:auto}.grid{display:grid;grid-template-columns:1.5fr 1fr;gap:20px}.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:20px}h2{font-size:17px;margin:0 0 18px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}.stat{background:var(--panel);border:1px solid var(--line);padding:18px;border-radius:12px}.value{font-size:25px;font-weight:650;margin-top:8px}canvas{width:100%;display:block;background:#0e1622;border-radius:10px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:12px 6px;border-bottom:1px solid var(--line)}label{display:block;color:var(--muted);margin:14px 0 6px}input,select,textarea{width:100%;padding:11px;background:#0d1622;border:1px solid #354961;border-radius:7px;color:var(--text);font:inherit}input[type=checkbox]{width:auto;margin-right:8px}input[type=file]{max-width:100%}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.hint{font-size:13px;line-height:1.6;color:var(--muted)}#notice{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#25473d;padding:14px 24px;border-radius:10px;max-width:90vw;z-index:10;display:none}progress{width:100%;height:14px;margin-top:16px}.hidden{display:none!important}.tag{border:1px solid var(--line);padding:7px 12px;border-radius:20px;font-size:13px}#targetRows td:first-child{color:var(--accent)}@media(max-width:850px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}header{align-items:flex-start;flex-direction:column}.card{padding:16px}}
</style></head><body>
<header><div><h1 id="title">ESP32 Sensor</h1><small>HLK-LD2450 · 이동 타깃 모니터</small></div><span id="connection" class="tag">연결 확인 중임</span></header>
<nav><button class="active" data-tab="dashboard">대시보드</button><button data-tab="map">지도</button><button data-tab="system">시스템</button></nav>
<main><section id="dashboard"><div class="stats"><div class="stat"><small>활성 타깃</small><div class="value" id="count">—</div></div><div class="stat"><small>유효 프레임</small><div class="value" id="frames">—</div></div><div class="stat"><small>수신 속도</small><div class="value" id="rate">—</div></div><div class="stat"><small>센서 상태</small><div class="value" id="health">—</div></div></div>
<div class="grid"><div><div class="card"><h2>타깃 위치</h2><canvas id="radar" width="760" height="460"></canvas><p class="hint">전방 6m · ±60° 기준 표시함. 원형 표시는 보정 좌표임. 타깃 번호는 센서 슬롯이며 동일 인물 식별을 보장하지 않음.</p></div><div class="card"><h2>수신 프레임 추이</h2><canvas id="signal" width="760" height="160"></canvas><p class="hint">UART 프레임 수신률 표시함. 모듈에서 원시 RF 파형을 제공하지 않아 RF 신호 그래프는 표시하지 않음.</p></div></div>
<div><div class="card"><h2>타깃 데이터</h2><table><thead><tr><th>타깃</th><th>x / y (mm)</th><th>속도 (cm/s)</th><th>분해능 (mm)</th></tr></thead><tbody id="targetRows"></tbody></table></div>
<div class="card"><h2>장치·표시 설정</h2><form id="deviceForm"><label>장치 이름</label><input name="name" maxlength="32" required><label>좌표 평활화 α</label><input name="alpha" type="number" min="0.05" max="1" step="0.05" required><label>표시 최대 거리 (mm)</label><input name="range" type="number" min="500" max="6000" step="100" required><label>프레임 만료 시간 (ms)</label><input name="stale" type="number" min="300" max="10000" step="100" required><label><input name="trails" type="checkbox" checked>이동 궤적 표시함</label><button class="primary" type="submit">설정 저장</button></form><p class="hint">수신 후 좌표 표시 처리에 적용함. LD2450 내부 감도·추적 모드는 변경하지 않음. α=1이면 평활화 없이 표시함.</p></div></div></div></section>
<section id="map" class="hidden"><div class="grid"><div><div class="card"><h2>평면도 위 타깃 위치</h2><canvas id="mapCanvas" width="983" height="739"></canvas><p class="hint">평면도 이미지 위에 보정값 기준으로 타깃을 표시함. 보정 전에는 위치가 정확하지 않음.</p></div></div>
<div><div class="card"><h2>지도 보정</h2><div class="row"><button id="mapSetOrigin" type="button">센서 위치 지정</button><button id="mapMeasureScale" type="button">축척 측정 (2점 클릭)</button></div><p id="mapArmHint" class="hint"></p>
<div id="mapScaleRow" class="row hidden"><div><label>실제 거리 (mm)</label><input id="mapRealDistance" type="number" min="1" max="100000" step="1"></div><button id="mapCalcScale" type="button">계산</button></div>
<label>방향 (도, 0=위쪽)</label><input id="mapHeading" type="number" min="0" max="359.9" step="0.5" value="0">
<label>축척 (mm/px)</label><input id="mapScale" type="number" min="0.5" max="500" step="0.01" value="10">
<button class="primary" id="mapSave" type="button">보정값 저장</button>
<p class="hint">센서 위치 지정 후 클릭한 지점이 센서 설치 위치가 됨. 방향은 센서 정면이 이미지에서 가리키는 각도(시계방향, 0=이미지 위쪽)임. 축척은 두 지점 클릭 후 실제 거리를 입력하면 자동 계산됨.</p></div></div></section>
<section id="system" class="hidden"><div class="grid"><div><div class="card"><h2>Wi-Fi 설정</h2><form id="wifiForm"><label>SSID</label><input name="ssid" maxlength="32" required><label>비밀번호</label><input name="password" type="password" maxlength="63" autocomplete="new-password" placeholder="빈칸이면 기존 값 유지함"><label><input name="open" type="checkbox">비밀번호 없는 Wi-Fi로 설정함</label><button class="primary" type="submit">저장 후 재연결</button></form><p class="hint">각 10초씩 총 5회 시도함. 실패하면 공개 AP ESP32-Sensor로 전환함. AP 접속 후 http://192.168.4.1 사용함.</p></div><div class="card"><h2>펌웨어 파일 업데이트</h2><form id="uploadForm"><input id="firmware" type="file" accept=".bin" required><p class="hint">이 보드용 firmware.bin 선택함. 성공하면 자동 재부팅함.</p><button class="primary" type="submit">업로드 및 업데이트</button><progress id="progress" max="100" value="0"></progress><p id="uploadStatus" class="hint">파일 선택 대기 중임</p></form></div></div>
<div><div class="card"><h2>자동업데이트</h2><form id="autoForm"><label><input name="enabled" type="checkbox">주기적으로 최신 버전 확인 및 설치함</label><label>버전 확인 URL</label><input name="versionUrl" type="url" placeholder="http://서버/version.txt"><label>펌웨어 URL</label><input name="binaryUrl" type="url" placeholder="http://서버/firmware.bin"><label>확인 주기 (분)</label><input name="interval" type="number" min="5" max="10080" required><label>HTTPS 서버 CA 인증서 (PEM)</label><textarea name="ca" rows="4" placeholder="HTTPS 사용 시 신뢰할 루트 CA 입력함"></textarea><div class="row"><button class="primary" type="submit">설정 저장</button><button id="checkUpdate" type="button">지금 확인 및 설치</button></div></form><p class="hint">version.txt는 1.0.1 형식의 버전 한 줄 제공함. 현재 버전보다 높으면 설치함. HTTPS는 CA 인증서와 시간 동기화 필요함.</p><p id="updateStatus" class="hint"></p></div>
<div class="card"><h2>시스템 정보</h2><table><tbody id="systemInfo"></tbody></table><p class="hint">AP는 요청한 공개 모드임. 접속자는 설정 변경 및 펌웨어 업데이트 가능함.</p><button id="restart">장치 재시작</button></div></div></div></section></main><div id="notice" role="status"></div>
<script>
const $=s=>document.querySelector(s),colors=['#66e1c2','#75a7ff','#f5bc6b'];let settingsLoaded=false,pollBusy=false,lastFrames=0,lastTime=0,history=[],trails=[[],[],[]],lastSequence=-1;
function toast(t){$('#notice').textContent=t;$('#notice').style.display='block';setTimeout(()=>$('#notice').style.display='none',5000)}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['dashboard','map','system'].forEach(t=>$('#'+t).classList.toggle('hidden',b.dataset.tab!==t))});
async function request(url,options){const r=await fetch(url,options);const d=await r.json();if(!r.ok)throw Error(d.message||'요청 실패함');return d}
function fill(form,data){for(const [k,v]of Object.entries(data)){const el=form.elements.namedItem(k);if(!el)continue;if(el.type==='checkbox')el.checked=v;else el.value=v}}
async function save(url,form){const data=new URLSearchParams(new FormData(form));form.querySelectorAll('input[type=checkbox]').forEach(el=>data.set(el.name,el.checked?'1':'0'));return request(url,{method:'POST',body:data})}
$('#deviceForm').onsubmit=async e=>{e.preventDefault();try{toast((await save('/api/device',e.target)).message)}catch(x){toast(x.message)}};
$('#wifiForm').onsubmit=async e=>{e.preventDefault();try{toast((await save('/api/wifi',e.target)).message);e.target.elements.password.value=''}catch(x){toast(x.message)}};
$('#autoForm').onsubmit=async e=>{e.preventDefault();try{toast((await save('/api/auto',e.target)).message)}catch(x){toast(x.message)}};
$('#checkUpdate').onclick=async()=>{try{toast((await request('/api/update/check',{method:'POST'})).message)}catch(x){toast(x.message)}};
$('#restart').onclick=async()=>{if(!confirm('장치 재시작함?'))return;try{toast((await request('/api/restart',{method:'POST'})).message)}catch(x){toast(x.message)}};
$('#uploadForm').onsubmit=e=>{e.preventDefault();const file=$('#firmware').files[0];if(!file||!file.name.endsWith('.bin'))return toast('.bin 파일 선택 필요함');if(!confirm('선택한 펌웨어 설치 후 재부팅함?'))return;const xhr=new XMLHttpRequest(),body=new FormData();body.append('firmware',file);const button=e.target.querySelector('button');button.disabled=true;xhr.open('POST','/api/update/upload');xhr.upload.onprogress=e=>{if(e.lengthComputable)$('#progress').value=e.loaded/e.total*100};xhr.onload=()=>{button.disabled=false;try{const data=JSON.parse(xhr.responseText);$('#uploadStatus').textContent=data.message;toast(data.message)}catch{$('#uploadStatus').textContent='응답 확인 실패함'}};xhr.onerror=()=>{button.disabled=false;$('#uploadStatus').textContent='연결 실패함. 장치 상태 확인 필요함'};$('#uploadStatus').textContent='전송 중임';xhr.send(body)};
function radar(d){const c=$('#radar'),x=c.getContext('2d'),w=c.width,h=c.height,ox=w/2,oy=h-28,scale=(h-55)/d.range;x.clearRect(0,0,w,h);x.strokeStyle='#29394c';x.fillStyle='#94a8be';x.font='12px system-ui';for(let r=1000;r<=d.range;r+=1000){x.beginPath();x.arc(ox,oy,r*scale,-Math.PI*5/6,-Math.PI/6);x.stroke();x.fillText(r/1000+'m',ox+5,oy-r*scale+14)}for(const a of [-60,0,60]){const rad=a*Math.PI/180;x.beginPath();x.moveTo(ox,oy);x.lineTo(ox+Math.sin(rad)*d.range*scale,oy-Math.cos(rad)*d.range*scale);x.stroke()}x.fillText('ESP32 / LD2450',ox-50,h-8);d.targets.forEach((t,i)=>{if(!t.present){trails[i]=[];return}const px=ox+t.fx*scale,py=oy-t.fy*scale;if(d.frames!==lastSequence){trails[i].push([px,py]);if(trails[i].length>35)trails[i].shift()}x.strokeStyle=colors[i];x.fillStyle=colors[i];if($('#deviceForm').elements.trails.checked){x.beginPath();trails[i].forEach((p,j)=>j?x.lineTo(...p):x.moveTo(...p));x.stroke()}x.beginPath();x.arc(px,py,7,0,Math.PI*2);x.fill();x.fillText('T'+(i+1),px+12,py-8)});lastSequence=d.frames}
function signal(rate){history.push(rate);if(history.length>90)history.shift();const c=$('#signal'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const max=Math.max(12,...history);x.strokeStyle='#29394c';for(let y=30;y<150;y+=40){x.beginPath();x.moveTo(0,y);x.lineTo(c.width,y);x.stroke()}x.strokeStyle='#66e1c2';x.beginPath();history.forEach((v,i)=>{const px=i*c.width/89,py=145-v/max*120;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#94a8be';x.fillText('frames/s · '+max.toFixed(0)+' max',12,18)}
const mapImg=new Image();let mapImgLoaded=false,mapDraft={x:491,y:719,heading:0,scale:10},mapOriginArmed=false,mapScaleArmed=false,mapScalePoints=[],lastStatusData=null;
mapImg.onload=()=>{mapImgLoaded=true;mapDraw()};mapImg.src='/mapview.png';
function mapPoint(e){const c=$('#mapCanvas'),r=c.getBoundingClientRect();return [(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}
function mapToPixel(fx,fy){const rad=mapDraft.heading*Math.PI/180,s=mapDraft.scale||10;return [mapDraft.x+(fx*Math.cos(rad)+fy*Math.sin(rad))/s,mapDraft.y+(fx*Math.sin(rad)-fy*Math.cos(rad))/s]}
function mapDraw(){const c=$('#mapCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(mapImgLoaded)x.drawImage(mapImg,0,0,c.width,c.height);const rad=mapDraft.heading*Math.PI/180;x.beginPath();x.arc(mapDraft.x,mapDraft.y,6,0,Math.PI*2);x.fillStyle='#66e1c2';x.fill();x.strokeStyle='#66e1c2';x.beginPath();x.moveTo(mapDraft.x,mapDraft.y);x.lineTo(mapDraft.x+Math.sin(rad)*30,mapDraft.y-Math.cos(rad)*30);x.stroke();mapScalePoints.forEach(p=>{x.beginPath();x.arc(p[0],p[1],5,0,Math.PI*2);x.fillStyle='#f5bc6b';x.fill()});if(!lastStatusData)return;lastStatusData.targets.forEach((t,i)=>{if(!t.present)return;const [px,py]=mapToPixel(t.fx,t.fy);x.beginPath();x.arc(px,py,8,0,Math.PI*2);x.fillStyle=colors[i];x.fill();x.fillStyle='#e7eef8';x.fillText('T'+(i+1),px+10,py-8)})}
$('#mapCanvas').onclick=e=>{const [px,py]=mapPoint(e);if(mapOriginArmed){mapDraft.x=px;mapDraft.y=py;mapOriginArmed=false;$('#mapArmHint').textContent='';mapDraw()}else if(mapScaleArmed){mapScalePoints.push([px,py]);if(mapScalePoints.length===2){mapScaleArmed=false;$('#mapArmHint').textContent='';$('#mapScaleRow').classList.remove('hidden')}mapDraw()}};
$('#mapSetOrigin').onclick=()=>{mapOriginArmed=true;mapScaleArmed=false;$('#mapArmHint').textContent='지도에서 센서 위치를 클릭함'};
$('#mapMeasureScale').onclick=()=>{mapScaleArmed=true;mapOriginArmed=false;mapScalePoints=[];$('#mapScaleRow').classList.add('hidden');$('#mapArmHint').textContent='거리를 아는 두 지점을 순서대로 클릭함'};
$('#mapCalcScale').onclick=()=>{if(mapScalePoints.length!==2)return;const dist=+$('#mapRealDistance').value;if(!dist||dist<=0)return toast('실제 거리 입력 필요함');const [a,b]=mapScalePoints,pxDist=Math.hypot(b[0]-a[0],b[1]-a[1]);if(pxDist<1)return toast('두 지점이 너무 가까움');mapDraft.scale=dist/pxDist;$('#mapScale').value=mapDraft.scale.toFixed(3);$('#mapScaleRow').classList.add('hidden');mapScalePoints=[];mapDraw()};
$('#mapHeading').oninput=e=>{mapDraft.heading=parseFloat(e.target.value)||0;mapDraw()};
$('#mapScale').oninput=e=>{mapDraft.scale=parseFloat(e.target.value)||mapDraft.scale;mapDraw()};
$('#mapSave').onclick=async()=>{try{const body=new URLSearchParams({x:mapDraft.x,y:mapDraft.y,heading:mapDraft.heading,scale:mapDraft.scale});toast((await request('/api/map',{method:'POST',body})).message)}catch(x){toast(x.message)}};
function rows(table,entries){table.replaceChildren();for(const cells of entries){const tr=document.createElement('tr');for(const text of cells){const td=document.createElement('td');td.textContent=text;tr.append(td)}table.append(tr)}}
async function poll(){if(pollBusy)return;pollBusy=true;try{const d=await request('/api/status');lastStatusData=d;$('#connection').textContent=d.network+' · '+d.ip;$('#title').textContent=d.name;$('#count').textContent=d.targets.filter(t=>t.present).length;$('#frames').textContent=d.frames;const now=performance.now(),rate=lastTime&&d.frames>=lastFrames?(d.frames-lastFrames)*1000/(now-lastTime):0;lastTime=now;lastFrames=d.frames;$('#rate').textContent=rate.toFixed(1)+' fps';$('#health').textContent=d.fresh?'정상':'수신 없음';radar(d);signal(rate);mapDraw();rows($('#targetRows'),d.targets.map((t,i)=>['T'+(i+1),t.present?t.x+' / '+t.y:'없음',t.present?t.speed:'—',t.present?t.resolution:'—']));rows($('#systemInfo'),[['펌웨어',d.version],['네트워크',d.network],['IP',d.ip],['Wi-Fi 시도',d.attempts+' / 5'],['RSSI',d.rssi===null?'—':d.rssi+' dBm'],['가동 시간',Math.floor(d.uptime/60)+'분'],['남은 Heap',Math.round(d.heap/1024)+' KB'],['수신 byte',d.bytes],['프레임 경과',d.age===null?'없음':d.age+' ms']]);$('#updateStatus').textContent=d.update;if(!settingsLoaded){const s=await request('/api/settings');fill($('#deviceForm'),s.device);fill($('#wifiForm'),{ssid:s.ssid});fill($('#autoForm'),s.auto);mapDraft={x:s.map.x,y:s.map.y,heading:s.map.heading,scale:s.map.scale};$('#mapHeading').value=mapDraft.heading;$('#mapScale').value=mapDraft.scale;settingsLoaded=true}}catch{$('#connection').textContent='장치 연결 끊김';$('#health').textContent='연결 없음';$('#count').textContent='—';$('#targetRows').replaceChildren();$('#radar').getContext('2d').clearRect(0,0,760,460);trails=[[],[],[]]}finally{pollBusy=false}}
poll();setInterval(poll,500);
</script></body></html>)HTML";
